name: braille_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  camera: ^0.10.5+5
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dots_indicator: ^4.0.1
  dotted_border: ^2.1.0
  file_picker: ^10.1.9
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  google_mlkit_text_recognition: ^0.15.0
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  syncfusion_flutter_pdf: ^29.2.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true,
  image_path: "assets/images/launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
